#!/usr/bin/env node
// Vendors @duffel/components' self-registering custom-elements bundle into a
// TS string module so the booking WebView can run it hermetically (no CDN,
// version-pinned to package-lock). Re-run after upgrading @duffel/components:
//   node scripts/vendor-duffel.js
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '..', 'node_modules', '@duffel', 'components', 'custom-elements.js');
const pkg = require(path.join(__dirname, '..', 'node_modules', '@duffel', 'components', 'package.json'));
const out = path.join(__dirname, '..', 'src', 'features', 'booking', 'duffelBundle.generated.ts');

const js = fs.readFileSync(src, 'utf8');
const banner = `// GENERATED by scripts/vendor-duffel.js from @duffel/components@${pkg.version} — do not edit.
// Self-registering <duffel-ancillaries> custom element (CJS bundle; the
// booking WebView shims module/exports before evaluating it).
/* eslint-disable */
export const DUFFEL_COMPONENTS_VERSION = ${JSON.stringify(pkg.version)};
export const DUFFEL_ANCILLARIES_JS: string = ${JSON.stringify(js)};
`;
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, banner);
console.log(`vendored @duffel/components@${pkg.version} → ${path.relative(process.cwd(), out)} (${(js.length / 1024).toFixed(0)} KB)`);
